export const add=async (req,res,next)=>{
    try {
     
    } catch (error) {
         res.status(500).json({mess:"Oops!... something went wrong"});
    } 
 }
 export const list=async (req,res,next)=>{
     try {
  
     } catch (error) {
          res.status(500).json({mess:"Oops!... something went wrong"});
     } 
  }
  export const edit=async (req,res,next)=>{
     try {
  
     } catch (error) {
          res.status(500).json({mess:"Oops!... something went wrong"});
     } 
  }
  export const remove=async (req,res,next)=>{
     try {
  
     } catch (error) {
          res.status(500).json({mess:"Oops!... something went wrong"});
     } 
  }